required_approvals = 1
block_labels = ["wip"]
delete_merged_branches = true
status = [
    "Rustfmt",
    "ci (%, stable)",
    "ci (stm32f401, stable)",
    "ci (stm32f405, stable)",
    "ci (stm32f407, stable)",
    "ci (stm32f410, stable)",
    "ci (stm32f411, stable)",
    "ci (stm32f412, stable)",
    "ci (stm32f413, stable)",
    "ci (stm32f415, stable)",
    "ci (stm32f417, stable)",
    "ci (stm32f423, stable)",
    "ci (stm32f427, stable)",
    "ci (stm32f429, stable)",
    "ci (stm32f437, stable)",
    "ci (stm32f439, stable)",
    "ci (stm32f446, stable)",
    "ci (stm32f469, stable)",
    "ci (stm32f479, stable)",
]
