language: rust
rust:
  - stable
  - nightly
cache: cargo
env:
- MCU=stm32f401
- MCU=stm32f407
- MCU=stm32f412
- MCU=stm32f429
- MCU=stm32f411
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7em-none-eabihf
  - cargo build --features=$MCU
